#!/usr/bin/python3

import os
import openai
import sys    

def main():
  # if no argument is passed, print error and exit
  if len(sys.argv) < 2:
      print("Error: No input file specified")
      sys.exit(1)

  # set bool execute to false if no -x is passed
  if sys.argv[1] == "-x":
      execute = True
      question= sys.argv[2]
  else:
      execute = False
      question= sys.argv[1]  

  openai.api_key = os.getenv("OPENAI_API_KEY")

  response = openai.Completion.create(
    model="text-davinci-002",
    prompt= "Tell me what you want to do and I will give the unix command.\n\nQ:  copy a file\ncp filename.txt destination_filename.txt\nQ: duplicate a folder?\ncp -a source_folder/ destination_folder/\nQ: display a calendar\ncal\nQ: convert a .heic file to jpg\nconvert source.heic destination.jpg\nQ: navigate to desktop\ncd ~/Desktop/\nQ: shutdown computer\nsudo shutdown -h now\nQ: check how much space is left on this computer\ndf -h\nQ: find x.txt on system\nfind . -name x.txt\nQ: delete entire dir and its contents\nrm -rf dir\nQ:  list the files in a directory\nls\nQ:" + question + "\nA: ",
    temperature=0.0,
    max_tokens=256,
    top_p=1,
    frequency_penalty=0,
    presence_penalty=0,
  )

  # remove \n from response
  response = response['choices'][0]['text'].replace("\n", "").strip()

  # if -x in argument, execute the command
  if "-x" in sys.argv:
    print('Executing: ' + response)
    os.system(response)
  else:
    print(response)


if __name__ == "__main__":
  main()